project:
  type: website

website:
  title: "assignment-3-ls2274"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - href: resources.qmd
        text: Resources
      - href: lok.qmd
        text: People
        

format:
  html:
    theme: quartz
    css: styles.css
    toc: true
    page-layout: full

